// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIqMmd_TVV3G_VUvEkbhsxGRJ3lvWA2s8',
    appId: '1:78545247170:web:a23245d95fd1daf893945b',
    messagingSenderId: '78545247170',
    projectId: 'servidor-db7ec',
    authDomain: 'servidor-db7ec.firebaseapp.com',
    storageBucket: 'servidor-db7ec.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2Rp7HFY1Uywx3WFAqyopxikWMq1ndUS4',
    appId: '1:78545247170:android:d9214cf29eb96ae493945b',
    messagingSenderId: '78545247170',
    projectId: 'servidor-db7ec',
    storageBucket: 'servidor-db7ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLiv3WgSQpcchT44jGXtchO-mAq2DDjK8',
    appId: '1:78545247170:ios:f09cf3b02c67de4593945b',
    messagingSenderId: '78545247170',
    projectId: 'servidor-db7ec',
    storageBucket: 'servidor-db7ec.appspot.com',
    iosBundleId: 'com.example.piazza',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLiv3WgSQpcchT44jGXtchO-mAq2DDjK8',
    appId: '1:78545247170:ios:f09cf3b02c67de4593945b',
    messagingSenderId: '78545247170',
    projectId: 'servidor-db7ec',
    storageBucket: 'servidor-db7ec.appspot.com',
    iosBundleId: 'com.example.piazza',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIqMmd_TVV3G_VUvEkbhsxGRJ3lvWA2s8',
    appId: '1:78545247170:web:50245eccbfd6788893945b',
    messagingSenderId: '78545247170',
    projectId: 'servidor-db7ec',
    authDomain: 'servidor-db7ec.firebaseapp.com',
    storageBucket: 'servidor-db7ec.appspot.com',
  );
}
